Improve performance in GHA (#3)

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,5 +1,5 @@
 ---
-name: 'Setup malbolge'
+name: 'Setup Malbolge'
 author: Yevhen Fabizhevskyi
 description: 'This action installs malbolge interpreter.'
 branding:
@@ -8,20 +8,16 @@ branding:
 runs:
   using: 'composite'
   steps:
-    - name: Fail
-      if: ${{ runner.os == 'macOS' }}
-      run: echo "::error::${{ runner.os }} ${{ runner.arch }} is not supported" && exit 1
-      shell: sh
-    - name: Collect info
-      if: ${{ runner.os != 'macOS' }}
-      id: info
-      run: |
-        MALBOLGE_INSTALLED=$(if command -v malbolge >/dev/null 2>&1; then echo true; else echo false; fi)
-        echo "MALBOLGE_INSTALLED=$MALBOLGE_INSTALLED" >> $GITHUB_OUTPUT
-      shell: sh
     - name: Install malbolge
-      if: ${{ runner.os != 'macOS' && steps.info.outputs.MALBOLGE_INSTALLED == 'false' }}
       run: |
-        gcc src/malbolge.c -o malbolge
-        echo "$GITHUB_WORKSPACE" >> $GITHUB_PATH
+        if ! command -v malbolge >/dev/null 2>&1; then
+          if [ "${{ runner.os }}" = "macOS" ]; then
+            echo "::error::${{ runner.os }} ${{ runner.arch }} is not supported"
+            exit 1
+          fi
+          gcc src/malbolge.c -o malbolge
+          echo "$GITHUB_WORKSPACE" >> $GITHUB_PATH
+        else
+          echo "::debug::$(which malbolge) is already installed"
+        fi
       shell: sh
