Bump pre-commit-hooks from 4.6.0 to 5.0.0 (#14)
## Changelog

- Update license copyright year to 2025

---

Powered by
[FantasticFiasco/action-update-license-year](https://github.com/FantasticFiasco/action-update-license-year)

---------

Co-authored-by: github-actions <github-actions@github.com>
Co-authored-by: fabasoad <fabasoad@gmail.com>

diff --git a/.github/workflows/functional-tests.yml b/.github/workflows/functional-tests.yml
--- a/.github/workflows/functional-tests.yml
+++ b/.github/workflows/functional-tests.yml
@@ -4,8 +4,16 @@ name: Functional Tests
 on: # yamllint disable-line rule:truthy
   push:
     branches:
-      - "main"
+      - main
   pull_request:
+    paths:
+      - .github/workflows/functional-tests.yml
+      - src/**
+      - action.yml
+  schedule:
+    # Every Friday at 09:00 JST
+    - cron: "0 0 * * 5"
+  workflow_dispatch: {}
 
 defaults:
   run:
@@ -24,7 +32,52 @@ jobs:
       - name: Checkout ${{ github.repository }}
         uses: actions/checkout@v4
       - name: Setup malbolge
+        id: setup-malbolge
         uses: ./
-      - name: Run script
+      - name: Test action completion
+        run: |
+          test_equal() {
+            if [ "${2}" != "${3}" ]; then
+              echo "::error title=${1}::Expected: ${3}. Actual: ${2}."
+              exit 1
+            fi
+          }
+          test_equal "malbolge should be installed" \
+            "${{ steps.setup-malbolge.outputs.installed }}" \
+            "true"
+      - name: Validate command
         run: |
           [ "$(malbolge hello-world.mal)" = "Hello, world." ] || exit 1;
+  test-force:
+    name: Test force
+    runs-on: ubuntu-latest
+    timeout-minutes: 5
+    strategy:
+      fail-fast: false
+      matrix:
+        force: ["true", "false"]
+    steps:
+      - name: Checkout ${{ github.repository }}
+        uses: actions/checkout@v4
+      - name: Setup malbolge 1
+        id: setup-malbolge-1
+        uses: ./
+      - name: Setup malbolge 2
+        id: setup-malbolge-2
+        uses: ./
+        with:
+          force: ${{ matrix.force }}
+      - name: Test action completion
+        run: |
+          test_equal() {
+            if [ "${2}" != "${3}" ]; then
+              echo "::error title=${1}::Expected: ${3}. Actual: ${2}."
+              exit 1
+            fi
+          }
+          test_equal "Wrong \"installed\" output from setup-malbolge-1" \
+            "${{ steps.setup-malbolge-1.outputs.installed }}" \
+            "true"
+          test_equal "Wrong \"installed\" output from setup-malbolge-2" \
+            "${{ steps.setup-malbolge-2.outputs.installed }}" \
+            "${{ matrix.force }}"
diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -5,19 +5,49 @@ description: "This action installs malbolge interpreter."
 branding:
   icon: terminal
   color: gray-dark
+inputs:
+  force:
+    description: |
+      If "false" skips installation if malbolge is already installed. If "true"
+      installs malbolge in any case. Defaults to "false".
+    required: false
+    default: "false"
+outputs:
+  installed:
+    description: Whether malbolge was installed or not.
+    value: "${{ steps.install-malbolge.outcome == 'success' }}"
 runs:
   using: "composite"
   steps:
-    - name: Install malbolge
+    - name: Fail
+      if: ${{ runner.os == 'macOS' }}
       run: |
-        if ! command -v malbolge >/dev/null 2>&1; then
-          if [ "${RUNNER_OS}" = "macOS" ]; then
-            echo "::error::${RUNNER_OS} ${RUNNER_ARCH} is not supported"
-            exit 1
-          fi
-          gcc src/malbolge.c -o malbolge
-          echo "$GITHUB_WORKSPACE" >> "$GITHUB_PATH"
-        else
-          echo "::debug::$(which malbolge) is already installed"
-        fi
+        echo "::error title=OS is not supported::${RUNNER_OS} ${RUNNER_ARCH} is not supported"
+        exit 1
       shell: sh
+
+    - name: Collect info
+      id: info
+      env:
+        INPUT_FORCE: "${{ inputs.force }}"
+      run: ./collect-info.sh "${INPUT_FORCE}"
+      shell: sh
+      working-directory: "${{ github.action_path }}/src"
+
+    - name: Install malbolge
+      if: ${{ steps.info.outputs.bin-installed == 'false' }}
+      id: install-malbolge
+      run: |
+        bin_path="${{ steps.info.outputs.bin-path }}"
+        mkdir -p "${bin_path}"
+        gcc malbolge.c -o "${bin_path}/malbolge"
+        echo "${bin_path}" >> "$GITHUB_PATH"
+      shell: sh
+      working-directory: ${{ github.action_path }}/src
+
+    - name: Print location
+      run: |
+        . ./logging.sh
+        log_info "malbolge is located at $(which malbolge)"
+      shell: sh
+      working-directory: "${{ github.action_path }}/src/lib"
